<?php

return [
    'id' => ['name' => 'Bahasa Indonesia', 'flag' => 'id', 'acronym' => 'ID', 'locale' => 'id'],
    'ms' => ['name' => 'Bahasa Malaysia', 'flag' => 'my', 'acronym' => 'MS', 'locale' => 'ms'],
    'en_GB' => ['name' => 'English (UK)', 'flag' => 'gb', 'acronym' => 'EN-UK', 'locale' => 'en_GB'],
    'en_US' => ['name' => 'English (US)', 'flag' => 'us', 'acronym' => 'EN-US', 'locale' => 'en_US'],
    'fr' => ['name' => 'Français', 'flag' => 'fr', 'acronym' => 'FR', 'locale' => 'fr'],
    'zh' => ['name' => '简体中文', 'flag' => 'cn', 'acronym' => 'cn', 'locale' => 'zh'],
    'de' => ['name' => 'Deutsch', 'flag' => 'de', 'acronym' => 'DE', 'locale' => 'de'],
    'es_MX' => ['name' => 'Español (MX)', 'flag' => 'mx', 'acronym' => 'ES-MX', 'locale' => 'es_MX'],
    'es_AR' => ['name' => 'Español (AR)', 'flag' => 'ar', 'acronym' => 'ES-AR', 'locale' => 'es_AR'],
    'pt_BR' => ['name' => 'Português (BR)', 'flag' => 'br', 'acronym' => 'PT-BR', 'locale' => 'pt_BR'],
    'pt_PT' => ['name' => 'Português (PT)', 'flag' => 'pt', 'acronym' => 'PT-PT', 'locale' => 'pt_PT'],
    'nl' => ['name' => 'Nederlands', 'flag' => 'nl', 'acronym' => 'NL', 'locale' => 'nl'],
    'it' => ['name' => 'Italiano', 'flag' => 'it', 'acronym' => 'IT', 'locale' => 'it'],
    'no' => ['name' => 'Norsk', 'flag' => 'no', 'acronym' => 'NO', 'locale' => 'no'],
    'fi' => ['name' => 'Suomi', 'flag' => 'fi', 'acronym' => 'FI', 'locale' => 'fi'],
    'sv' => ['name' => 'Svenska', 'flag' => 'se', 'acronym' => 'SV', 'locale' => 'sv'],
    'da' => ['name' => 'Dansk', 'flag' => 'dk', 'acronym' => 'DA', 'locale' => 'da'],
    'ja' => ['name' => '日本語', 'flag' => 'jp', 'acronym' => 'JA', 'locale' => 'ja'],
    'el' => ['name' => 'Ελληνικά', 'flag' => 'gr', 'acronym' => 'EL', 'locale' => 'el'],
    'ru' => ['name' => 'Русский', 'flag' => 'ru', 'acronym' => 'RU', 'locale' => 'ru'],
    'tr' => ['name' => 'Türkçe', 'flag' => 'tr', 'acronym' => 'TR', 'locale' => 'tr'],
    'ar' => ['name' => 'العربية', 'flag' => 'sa', 'acronym' => 'AR', 'locale' => 'ar'],
    'uk' => ['name' => 'Українська', 'flag' => 'ua', 'acronym' => 'UK', 'locale' => 'uk'],
    'hi' => ['name' => 'हिन्दी', 'flag' => 'in', 'acronym' => 'HI', 'locale' => 'hi'],
    'ko' => ['name' => '한국어', 'flag' => 'kr', 'acronym' => 'KO', 'locale' => 'ko'],
    'he' => ['name' => 'עברית', 'flag' => 'il', 'acronym' => 'HE', 'locale' => 'he'],
    'th' => ['name' => 'ภาษาไทย', 'flag' => 'th', 'acronym' => 'TH', 'locale' => 'th'],
    'hu' => ['name' => 'Magyar', 'flag' => 'hu', 'acronym' => 'HU', 'locale' => 'hu'],
    'ro' => ['name' => 'Română', 'flag' => 'ro', 'acronym' => 'RO', 'locale' => 'ro'],
    'pl' => ['name' => 'Polski', 'flag' => 'pl', 'acronym' => 'PL', 'locale' => 'pl'],
    'bg' => ['name' => 'Български', 'flag' => 'bg', 'acronym' => 'BG', 'locale' => 'bg'],
    'lt' => ['name' => 'Lietuvių', 'flag' => 'lt', 'acronym' => 'LT', 'locale' => 'lt'],
    'lv' => ['name' => 'Latviski', 'flag' => 'lv', 'acronym' => 'LV', 'locale' => 'lv'],
    'hr' => ['name' => 'Hrvatski', 'flag' => 'hr', 'acronym' => 'HR', 'locale' => 'hr'],
    'sl' => ['name' => 'Slovenščina', 'flag' => 'si', 'acronym' => 'SL', 'locale' => 'sl'],
    'is' => ['name' => 'Íslenska', 'flag' => 'is', 'acronym' => 'IS', 'locale' => 'is'],
    'vi' => ['name' => 'Tiếng Việt', 'flag' => 'vn', 'acronym' => 'VI', 'locale' => 'vi'],
    'tl' => ['name' => 'Filipino', 'flag' => 'ph', 'acronym' => 'TL', 'locale' => 'tl'],
];
